= Appendix: Quick reference

== The bare bones

xref:execution.adoc#printing[Comments]: ::

From `%%` to end of line.

xref:execution.adoc#printing[Special characters]: ::

`#`, `$`, `@`, `~`, `*`, `|`,
`\`, parentheses, brackets, and braces. Prefix by `\` to
print.

xref:execution.adoc#predicates[Rule definitions]: ::

* The rule head is in the leftmost column.
* The rule body is a sequence of statements, not in the leftmost column. They
form a conjunction.
* Multiple rule definitions for the same predicate are tried in order. They form
a disjunction.
* Queries succeed or fail. Failure causes xref:choicepoints.adoc#backtracking[backtracking].
* xref:sugar.adoc#nested[Nested queries] and xref:sugar.adoc#slash[slash expressions] can only appear in heads, not bodies.

Statements: ::

* xref:execution.adoc#predicates[Queries] (normal, negated, or xref:choicepoints.adoc#multi-query[multi-]) to predicates,
* xref:execution.adoc#printing[text to be printed], or
* special syntax.

Value syntax:

#abc::

xref:execution.adoc#parameters[Object name].

@abc::

xref:varsvalues.adoc#dictwords[Dictionary word]. The `@` is optional inside list expressions. Special words to represent xref:io.adoc#getkey[non-printable keys]: `@\n`, `@\b`,
`@\s`, `@\u`, `@\d`, `@\l`,
`@\r`.

$abc::

xref:varsvalues.adoc#local-variables[Variable].

123::

xref:varsvalues.adoc#numbers[Number] (the valid range is 0–16383).

[]::

xref:varsvalues.adoc#lists[Empty list].

[ _element1_ _element2_ _element3_ _..._ ]::

xref:varsvalues.adoc#lists[Complete list].

[ _element1_ _element2_ _element3_ _..._ | _tail_ ]::

xref:varsvalues.adoc#partiallists[Partial list].

{ _..._ }::

xref:control.adoc#closures[Closure].

* ::

xref:sugar.adoc#current-topic[Current topic].

The current topic is set with an object name in the leftmost column.

A/B/C ::

xref:sugar.adoc#slash[Alternatives] (in rule heads only).

xref:varsvalues.adoc#unification[Unification]: ::

* Arguments are passed by unification.
* Simple values unify with themselves.
* Lists unify when each element unifies.
* Unbound variables unify (with values or unbound variables) by binding.

[#special]
== Special syntax

xref:choicepoints.adoc#disjunction[{ ... }]::

Conjunction.

xref:control.adoc#negation[~{ ... }]::

Negated conjunction.

xref:choicepoints.adoc#disjunction[... (or) ... (or) ...]::

Disjunction.

xref:control.adoc#if[(if) ... (then) ... (elseif) ... (then) ... (else) ... (endif)] ::

Conditions are evaluated at most once. Missing else-clause is assumed to be
empty, i.e. succeeds.

xref:control.adoc#select-var[(select) ... (or) ... (or) ... (stopping)]::

Branches entered one at a time, then the final branch repeats.

xref:control.adoc#select-var[(select) ... (or) ... (or) ... (cycling)]::

Branches entered one at a time, then the cycle repeats.

xref:control.adoc#select-var[(select) ... (or) ... (or) ... (at random)]::

Branches entered at random, avoiding repetition.

xref:control.adoc#select-var[(select) ... (or) ... (or) ... (purely at random)]::

Branches entered at random, allowing repetition.

xref:control.adoc#select-var[(select) ... (or) ... (or) ... (then at random)]::

First like `(select) ... (stopping)`, then like `(select) ... (at
random)`.

xref:control.adoc#select-var[(select) ... (or) ... (or) ... (then purely at random)]::

First like `(select) ... (stopping)`, then like
`(select) ... (purely at random)`.

xref:choicepoints.adoc#exhaust[(exhaust) _statement_] ::

Backtracks over all solutions to the statement (typically a block).

xref:choicepoints.adoc#collect-values[(collect $Element) ... (into $List)]::

Backtracks over all solutions to the inner expression. Values bound to
`$Element` are collected in order and unified with `$List`.

xref:choicepoints.adoc#collect-words[(collect words) ... (into $List)]::

Backtracks over all solutions to the inner expression, grabbing all output.
Printed words are diverted into `$List`, possibly out of order.

xref:choicepoints.adoc#accumulate[(accumulate $Element) ... (into $Sum)]::

Backtracks over all solutions to the inner expression. Values bound to
`$Element` are added and their sum is unified with `$Sum`.

xref:io.adoc#determine-object[(determine object $Obj) ... (from words) ... (matching all of $List)]::

Backtracks over every object `$Obj` that makes the first inner expression
succeed, and for which the second expression (when exhausted) emits at least
every word in `$List`.

xref:control.adoc#stoppable[(stoppable) _statement_]::

The inner statement executes, succeeding at most once. The `(stop)`
built-in breaks out of the innermost stoppable environment. The stoppable
environment itself always succeeds.

xref:io.adoc#div[(span $Class) _statement_]::

The inner statement executes, succeeding at most once. All output is rendered
according to the given style class.

xref:io.adoc#div[(div $Class) _statement_]::

The inner statement executes, succeeding at most once. All output is rendered
into a rectangular area according to the given style class.

xref:io.adoc#status[(status bar $Class) _statement_]::

Like `(div $)`, but the output is rendered into the top status area,
which is created if necessary.

xref:io.adoc#sizing[(status bar $Class with height $Height) _statement_]::

Like `(status bar $)`, but if its second parameter is bound to a number,
attempts to set the top status area’s height to that value.

xref:io.adoc#status[(inline status bar $Class) _statement_]::

Like `(div $)`, but the output is rendered into an inline status area.
The previous inline status area, if any, is removed from display.

xref:io.adoc#links[(link) _statement_]::

The inner statement executes, succeeding at most once. The interpreter displays
the output, optionally in the form of a hyperlink. If the hyperlink is selected
by the player, the output from the inner statement is appended to the current
input buffer, which is submitted.

xref:io.adoc#links[(link $Words) _statement_]::

The inner statement executes, succeeding at most once. The interpreter displays
the output, optionally in the form of a hyperlink. If the hyperlink is selected
by the player, the given `$Words` are appended to the current input
buffer, which is submitted.

xref:io.adoc#resources[(link resource $Id) _statement_]::

The inner statement executes, succeeding at most once. The interpreter displays
the output, optionally in the form of a hyperlink. The hyperlink leads to the
resource identified by `$Id`.

xref:io.adoc#debugging[(log) _statement_]::

If running in the debugger, execute the inner statement in a stoppable
environment. The output appears between line breaks, in a distinct style.
Otherwise, do nothing.

xref:dynamic.adoc[(now) _pseudo-query_]::

Updates a dynamic predicate.

xref:choicepoints.adoc#just[(just)]::

Removes choice-points created since the current predicate was queried.

xref:dynamic.adoc#globvar[(global variable (name of predicate $))]::

Declares a global variable.

xref:beyondprog.adoc#interface[(interface (name of predicate))]::

Declares an interface, i.e. the intended use of a predicate.

xref:sugar.adoc#generate[(generate $N (name of predicate $))]::

Creates `$N` anonymous objects, for which the predicate will succeed.

xref:sugar.adoc#accesspred[@(...) ...]::

Defines an access predicate. Queries or definitions matching the rule head are
transformed into the rule body at compile-time.

== Built-in predicates

The list is sorted alphabetically, considering just the non-parameter words.

xref:varsvalues.adoc#unification[($X = $Y)]::

Unifies `$X` with `$Y`.

xref:builtins.adoc#arithmetic[($X < $Y)]::

Succeeds if `$X` and `$Y` are numbers, and `$X` is strictly
less than `$Y`.

xref:builtins.adoc#arithmetic[($X > $Y)]::

Succeeds if `$X` and `$Y` are numbers, and `$X` is strictly
greater than `$Y`.

xref:builtins.adoc#listbuiltins[(append $A $B $AB)]::

Unifies `$AB` with the concatenation of `$A` (which must be bound)
and `$B`.

xref:io.adoc#case[(bold)]::

Enables bold text.

xref:builtins.adoc#typechecks[(bound $X)]::

Succeeds if `$X` is bound to a value.

xref:io.adoc#debugging[(breakpoint)]::

Suspends execution if running in the debugger.

xref:io.adoc#clear[(clear)]::

Clears the main window, but not the top status area.

xref:io.adoc#clear[(clear all)]::

Clears the screen and disables the top status area.

xref:io.adoc#clear[(clear div)]::

Clears or hides the current div.

xref:io.adoc#links[(clear links)]::

Transforms all hyperlinks into plain text, except in the status areas.

xref:io.adoc#clear[(clear old)]::

Clears the screen from all text that the player has had a chance to read.

xref:io.adoc#clear[(clear status bar)]::

Removes all status areas (top and inline).

xref:beyondprog.adoc#metadata[(compiler version)]::

Prints the name and version of the compiler.

xref:io.adoc#sizing[(current div width $)]::

Unifies its parameter with the width of the current div, in characters.

xref:io.adoc#sizing[(current div height $)]::

Unifies its parameter with the height of the current div, in ems.

xref:beyondprog.adoc#runtimeerror[(display memory statistics)]::

Displays a backend-specific paragraph of memory usage statistics.

xref:builtins.adoc#arithmetic[($X divided by $Y into $Z)]::

Unifies `$Z` with the quotient after dividing `$X` by `$Y`.

xref:io.adoc#resources[(embed resource $Id)]::

Displays the resource identified by `$Id`, embedded in the story text.

xref:builtins.adoc#typechecks[(empty $X)]::

Succeeds if `$X` is bound to an empty list.

xref:choicepoints.adoc#exhaust[(fail)]::

Fails. Equivalent in functionality to e.g. `(1 = 2)`.

xref:io.adoc#case[(fixed pitch)]::

Enables fixed-pitch text.

xref:builtins.adoc#typechecks[(fully bound $X)]::

Succeeds if `$X` is bound to a value, and—in case of a list—contains only
fully bound elements.

xref:io.adoc#getinput[(get input $)]::

Reads a line of input from the player. Returns a list of words.

xref:io.adoc#getkey[(get key $)]::

Waits for the player to press a key. Returns a single-character word.

xref:dynamic.adoc#hasparent[($X has parent $Y)]::

Dynamic predicate that succeeds when `$X` is a direct child of
`$Y` in the object tree. Either parameter can be unbound.

xref:io.adoc#resources[(interpreter can embed $Id)]::

Succeeds if the current interpreter supports the resource identified by
`$Id`, and is able to display it using `(embed resource $Id)`
without falling back on just printing the alt-text.

xref:io.adoc#status-inline[(interpreter supports inline status bar)]::

Succeeds if the current interpreter supports inline status areas.

xref:io.adoc#links[(interpreter supports links)]::

Succeeds if the current interpreter claims to support hyperlinks, and they are
currently enabled. This can change at runtime, for instance if a game is saved
and subsequently restored on a different interpreter.

xref:builtins.adoc#system[(interpreter supports quit)]::

Succeeds if the current interpreter supports quit in a way that is meaningful to
the player. This can change at runtime, for instance if a game is saved and
subsequently restored on a different interpreter.

xref:io.adoc#top-status[(interpreter supports status bar)]::

Succeeds if the current interpreter supports the top status area.

xref:builtins.adoc#system[(interpreter supports undo)]::

Succeeds if the current interpreter claims to support undo. This can change at
runtime, for instance if a game is saved and subsequently restored on a
different interpreter.

xref:builtins.adoc#listbuiltins[($X is one of $Y)]::

Unifies `$X` with each element of `$Y` in turn.

xref:io.adoc#case[(italic)]::

Enables italic text.

xref:builtins.adoc#dictbuiltins[(join words $List into $Word)]::

Concatenates the dictionary words (or numbers) in `$List` into a new
dictionary word (or number), and unifies the result with `$Word`.

xref:execution.adoc#printing[(line)]::

Requests a line break.

xref:builtins.adoc#typechecks[(list $X)]::

Succeeds if `$X` is bound to a list (empty or non-empty).

xref:builtins.adoc#arithmetic[($X minus $Y into $Z)]::

Unifies `$Z` with the difference between `$X` and `$Y`.

xref:builtins.adoc#arithmetic[($X modulo $Y into $Z)]::

Unifies `$Z` with the remainder after dividing `$X` by
`$Y`.

xref:execution.adoc#nbsp[(nbsp)]::

Inserts a non-breaking space before the next word.

xref:builtins.adoc#typechecks[(nonempty $X)]::

Succeeds if `$X` is bound to an non-empty list.

xref:execution.adoc#printing[(no space)]::

Inhibits automatic whitespace before the next word or punctuation mark.

xref:builtins.adoc#typechecks[(number $X)]::

Succeeds if `$X` is bound to a number.

xref:builtins.adoc#typechecks[(object $X)]::

Checks if `$X` is an object, or—in a multi-query—backtracks over every
object.

xref:execution.adoc#printing[(par)]::

Requests a paragraph break.

xref:io.adoc#progress[(progress bar $ of $)]::

Draws a progress bar scaled to fit the width of the current div.

xref:builtins.adoc#arithmetic[($X plus $Y into $Z)]::

Unifies `$Z` with the sum of `$X` and `$Y`.

xref:builtins.adoc#system[(quit)]::

Immediately terminates the interpreter.

xref:builtins.adoc#arithmetic[(random from $X to $Y into $Z)]::

Unifies `$Z` with a random number in the range `$X` to `$Y`
inclusive.

xref:choicepoints.adoc#repeat[(repeat forever)]::

Provides an infinite supply of choice points. Generally invoked with a
multi-query.

xref:builtins.adoc#system[(restart)]::

Restarts the program.

xref:builtins.adoc#system[(restore)]::

Restores a saved game (the interpreter asks for a filename).

xref:io.adoc#case[(reverse)]::

Enables reverse-video text.

xref:io.adoc#case[(roman)]::

Disables all text styles (bold, italic, reverse, and fixed pitch).

xref:builtins.adoc#system[(save $ComingBack)]::

Saves the current game (the interpreter asks for a filename). Unifies
`$ComingBack` with 0 after a successful save, 1 after a successful
restore.

xref:builtins.adoc#system[(save undo $ComingBack)]::

Saves the current program state in memory. Unifies `$ComingBack` with 0
after a successful save, 1 after a successful restore.

xref:beyondprog.adoc#metadata[(serial number)]::

Prints the serial number (compilation date) of the current program.

xref:execution.adoc#printing[(space)]::

Forces whitespace before the next word or punctuation mark.

xref:io.adoc#case[(space $N)]::

Prints `$N` space characters.

xref:builtins.adoc#split[(split $X by $Y into $Left and $Right)]::

Splits `$X` into two halves around each occurrence of `$Y` or any
member of `$Y`.

xref:builtins.adoc#wordbuiltins[(split word $Word into $List)]::

Converts the dictionary word (or number) `$Word` into a list of its
constituent characters, and unifies the result with `$List`.

xref:lang:control.adoc#stoppable[(stop)]::

Breaks out of the innermost `(stoppable)` environment.

xref:builtins.adoc#arithmetic[($X times $Y into $Z)]::

Unifies `$Z` with the product of `$X` and `$Y`.

xref:io.adoc#debugging[(trace off)]::

Disables query tracing.

xref:io.adoc#debugging[(trace on)]::

Enables query tracing.

xref:builtins.adoc#system[(transcript off)]::

Disables transcription.

xref:builtins.adoc#system[(transcript on)]::

Enables transcription (the interpreter asks for a filename).

xref:builtins.adoc#system[(undo)]::

Restores the program state at the time of the latest `(save undo 0)`.

xref:builtins.adoc#typechecks[(unknown word $X)]::

Succeeds if `$X` is bound to a word that wasn't found in the game
dictionary.

xref:io.adoc#case[(unstyle)]::

Select the default text style for the current division.

xref:io.adoc#case[(uppercase)]::

Convert the next printed character to uppercase.

xref:builtins.adoc#typechecks[(word $X)]::

Succeeds if `$X` is bound to a dictionary word.

== Entry points and metadata predicates

xref:beyondprog.adoc#runtimeerror[(error $ErrorCode entry point)]::

Execution restarts here when a fatal error has occurred.

xref:execution.adoc#predicates[(program entry point)]::

Normal execution starts here.

xref:beyondprog.adoc#metadata[(story author)]::

Metadata: Defines the author of the story.

xref:beyondprog.adoc#metadata[(story blurb)]::

Metadata: Defines the blurb for the story.

xref:beyondprog.adoc#metadata[(story ifid)]::

Metadata: Defines the IFID of the story.

xref:beyondprog.adoc#metadata[(story noun)]::

Metadata: Defines the noun (also known as the headline) of the story.

xref:beyondprog.adoc#metadata[(story release $N)]::

Metadata: Defines the release number of the story.

xref:beyondprog.adoc#metadata[(story title)]::

Metadata: Defines the title of the story.

xref:beyondprog.adoc#metadata[(library version)]::

Defines the library version and is used to identify the library source code
file.

xref:io.adoc#getinput[(removable word endings)]::

Defines one or more word endings that can be removed when parsing user input.

xref:io.adoc#div[(style class $Name)]::

Associates one or more style attributes with the given class name.

xref:io.adoc#resources[(define resource $Id)]::

Defines the location (local filename or URL), options, and alt-text of a resource.

