# This playbook is used to build "snapshot" versions of the manual for testing
# or inclusion in the standalone zip.
site:
  title: Dialog (snapshot)
  start_page: dialog::index.adoc
content:
  sources:
    - url: ./..
      branches: HEAD
      start_path: manual
ui:
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/HEAD/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: true
